name: elec576-a2
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.1
  - torchvision>=0.16
  - torchaudio>=2.1
  - numpy>=1.24
  - matplotlib>=3.7
  - pandas>=2.0
  - scikit-learn>=1.3
  - tqdm>=4.65
  - pip
